server:
  port: 8084
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: rest-client
          uri: http://127.0.0.1:8090
          predicates:
            - Path=/rest/projects/**
          filters:
            - StripPrefix=1
        - id: panache-service
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/service/projects/**
          filters:
            - StripPrefix=1
        - id: mybatis-service
          uri: http://127.0.0.1:8884
          predicates:
            - Path=/mybatis/projects/**
          filters:
            - StripPrefix=1
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka/